### ISSUE TITLE
geodata table schema to example

### ISSUE THREAD

**Issue by tedx** [michaelpq/michaelpq.github.io#1]
2014-04-06-postgres-9-4-feature-highlight-indexing-jsonb
I wanted to play with your jsonb indexing exmaple but I don't see the CREATE TABLE for geodata. How did you create it?

**Comment by michaelpq** [comment]
Sorry for the late reply, simply tweak a CREATE TABLE command with correct types here:
http://download.geonames.org/export/dump/readme.txt
You can just go with text instead of char and varchar, and numeric for latitude and longitude. If you don't want to think, simply use text as well for the modification date.
